### ISSUE TITLE
Reading input files from VASP

### ISSUE THREAD

**Issue by WangLulu97** [Probe-Particle/PPSTM#1]
Hi,

I have successfully read the VASP output LOCPOT to use the PPAFM. But for PPSTM, it cannot read VASP output right now.

In VASP, the WAVECAR file contains predicted wavefunctions compatible with CONTCAR. If set LPARD, NBMOD, and EINT, it could calculate the band decomposed charge densities into PARCHG.

Could you help to make the PPSTM could read the WAVECAR or PARCHG file from the VASP? That would really help a lot.

Thank you very much!

**Comment by ondrejkrejci** [comment]
Hi,

Thank you for your issue! I have to dissapoint you, but reading wavefunctions from VASP or any other Plane Waves (PW) codes is not possible. The whole formalism of PP-STM is based on Linear Combination of Atomic Orbitals and we found no way, how to project the PW formalism of VASP to LCAO, without loosing the knowledge of the phase (which is an important part for the interference effects).
So far we were using workflow of having the geometry from VASP and then used some LCAO code like FHI-aims, CP2K (GLP code) or GPAW-lcao (also GPL) to calculate the electronic structure throu single-point calculations (no opt). Beware the official version of PP-STM is working only w. Gamma point, so sometimes larger cell for the single point calculation is needed.
If you need a help with setting the electronic calculations with LCAO, then let me know.
If there is a bigger market for other LCAO codes (e.g. Siesta) then this could be also done, but it would take some time.
Thank you for your understanding and good luck with your project!
Regards,
Ondrej

**Comment by WangLulu97** [comment]
Really thank you for your quick reply! Wish you all the best!
