### ISSUE TITLE
All tests involving relaxed scanning fail

### ISSUE THREAD

**Issue by LauriKurki** [Probe-Particle/PPSTM#14]
As PPAFM has seen major changes, now some of the features of PPSTM dependent on PPAFM have been broken as mentioned in #12. For example running `tests/4N-coronene/run_test.sh` fails as the LJ field used to be generated with `python PATH_TO_YOUR_PROBE_PARTICLE_MODEL/generateLJFF.py -i YOUR_INPUT_FILE.cube --npy` but the `--npy` option has been replaced with `-f npy`. Example error attached.

![image](https://user-images.githubusercontent.com/37794515/204537218-84245f27-f728-4833-95e3-6561dc5530f9.png)

This requires at least changing the way PPAFM is called within PPSTM.

**Comment by ondrejkrejci** [comment]
Once more, please could you check with the newest npy version? Thank you!

**Comment by LauriKurki** [comment]
Thanks for the update and sorry for the delay!

A couple of problems remain, and I think I can fix these apart from number 4:

1. In PPAFM, the module pyProbeParticle was renamed to ppafm so all the imports have to be renamed in PPSTM as well 
2. Location and usage of e.g. generateLJFF.py has changed in PPAFM so instructions for generating the LJ and electrostatic FFs has to be updated as well.
3. Installing PPAFM should be done with `pip install ppafm==0.2.0a1` now instead of the script. With this we could use `ppafm-generate-ljff` etc. for the force fields
4. Saving the atoms within PPAFM seems to be not working, I'm commenting more in here https://github.com/Probe-Particle/ppafm/issues/53
