### ISSUE TITLE
Change which branch of PPAFM is installed

### ISSUE THREAD

**Issue by LauriKurki** [Probe-Particle/PPSTM#15]
### Problem

If I remember correctly, the current main branch of PPAFM is the old OpenCL_py3 branch and the old `main` branch is now `master_backup`. The problem is that the current `main` branch is very different from `master_backup` and PPSTM doesn't work correctly with the new `main` branch, at least for the test molecules in PPSTM. This is a big problem because currently PPSTM is essentially broken.

### Suggestion

To make PPSTM work again, we should  for now install the `master_backup` branch of PPAFM in [install_PPAFM.sh](https://github.com/Probe-Particle/PPSTM/blob/d23186248d8c921286e97baeedf748608dbbfcd3/install_PPAFM.sh) instead of the main branch. If we want to make PPSTM work again with the main branch of PPAFM, we have to work with PPAFM code.

**Comment by ondrejkrejci** [comment]
@LauriKurki Please could you check with the newest version of ppafm? Maybe we can close this issue.

**Comment by ondrejkrejci** [comment]
Checked, everything except FePc_Au is working.
