### ISSUE TITLE
The way of tuning tip-model orbital in random proportion

### ISSUE THREAD

**Issue by TaoTaotheCreator** [Probe-Particle/PPSTM#31]
Hi, I just trying to simulate STM images using different tip-model to compare with my experiments, and the wiki said `better is to calculate s and pxy in two separated runs and save it as npy or xsf. Then you can use SUM_Orb_Contrib.py script to print you any configurations between s and pxy tip-atom orbitals. This is possible, since contributions from different tip-atom orbitals can be simply summed-up.` , so could you please tell me the detailed way to get the random tip-model with any orbital proportions, such as 3%s 97%pxy? Thanks a lot!

**Comment by LauriKurki** [comment]
Hi!

If you have calculated the _s_ and _pxy_ scans with `PPSTM_simple.py`, you can use the `SUM_Orb_contrib.py` to tweak the exact orbital contributions you want.

https://github.com/Probe-Particle/PPSTM/blob/96b04802c278a22b14d81d382fc115fcede158b8/SUM_Orb_Contrib.py#L23-L33

i.e. here on lines 24 and 25 you should set `tip_orb1 = 's'` and `tip_orb2 = 'pxy'` and on lines 30-31 you can choose the ratios. Does this help or is there something more specific we can assist with?

**Comment by ondrejkrejci** [comment]
Hi,

Two answers makes sense depending on a size of your system:

- if the system is small (molecule, up to 30 atoms), go and try the calculations in the GUI that we have developed. You will get a pretty quick idea of what is going on. 

- if the system is big (you have also substrate, which needs to be huge, since we do not have working k-points version)

I would suggest to copy [PPSTM_simple.py](https://github.com/Probe-Particle/PPSTM/blob/master/PPSTM_simple.py) script twice to the directory you are working, one with name `s` and one with `pxy`. Adjust the parameters at the top of the files to what you need (_dIdV_ or _V-scan_ ... ) and set the output to `npy` and then follow @LauriKurki 's suggestion about the `SUM_Orb_Contrib.py`. Also I suggest to copy it to your working directory. As far as I remember, you can run it many times with different settings, it will name the outputs (just leave it to png) according to the orbitals and ratio used.

**Comment by TaoTaotheCreator** [comment]
OK , I will have a try, thanks!

**Comment by TaoTaotheCreator** [comment]
I have installed PPAFM in the same environment of PPSTM, but the error came below:
`writing npy binary files
Traceback (most recent call last):
  File "pxy.py", line 374, in <module>
    io.saveNpy(name_file, didv[vv], lvec)#, head=XSF_HEAD_DEFAULT )
TypeError: saveNpy() missing 1 required positional argument: 'atomic_info'`

**Comment by ondrejkrejci** [comment]
Hi, this is looks like a bug in the PPSTM code. Could you please upload the pxy.py file and tell us, where is it comming from?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by TaoTaotheCreator** [comment]
[pxy.zip](https://github.com/user-attachments/files/16940686/pxy.zip)

**Comment by TaoTaotheCreator** [comment]
I think maybe the error lie in the positional argument are provided not enough, but I donot find the missing parameter.

**Comment by ondrejkrejci** [comment]
![Screenshot_20220314_142445](https://github.com/user-attachments/assets/3cd90f7b-58e2-4c0d-a21a-b8196faaca62) You need to change the line 374 and 377 in both as you can see here. You will need to change the whole PPSTM_simple, to be working properly, at some point.

**Comment by ondrejkrejci** [comment]
![Screenshot from 2024-09-10 12-21-06](https://github.com/user-attachments/assets/5a393266-c956-481b-bfc8-15a5375c3883)
Hi, you need to change line 374 and 377 accordingly.
Ondrej

**Comment by ondrejkrejci** [comment]
Anyway, the best would be to git pull the latest PPSTM version, which has it repaired. And to create the pxy.py from the latest version of the `PPSTM_simple.py`.

**Comment by TaoTaotheCreator** [comment]
Yes, I got the latest PPSTM_simple.py, and it ran well!! But when I got the .npz files, I ran the `SUM_Orb_contrib.py`, the error came as below:
```
Importing STM data for V: -2.0
Traceback (most recent call last):
  File "SUM_Orb_Contrib.py", line 122, in <module>
    tmp_stm1, lvec1, nDim1, atomic_info_or_head = io.load_scal_field( files_path+name_file1 ,data_format=data_format)
  File "/public4/home/sc53074/software/anaconda3/envs/PPSTM1/lib/python3.7/site-packages/ppafm/io.py", line 933, in load_scal_field
    data, lvec, atomic_info_or_head = loadNpy(fname)
  File "/public4/home/sc53074/software/anaconda3/envs/PPSTM1/lib/python3.7/site-packages/ppafm/io.py", line 758, in loadNpy
    atomic_info = (tmp_input["atoms"], tmp_input["lvec0"])
  File "/public4/home/sc53074/software/anaconda3/envs/PPSTM1/lib/python3.7/site-packages/numpy/lib/npyio.py", line 256, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/public4/home/sc53074/software/anaconda3/envs/PPSTM1/lib/python3.7/site-packages/numpy/lib/format.py", line 743, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```
Maybe it came from the contradict in the version of Numpy.

**Comment by LauriKurki** [comment]
I tried to load a didv image from a `.npz ` file with numpy version 1.24.3 and I couldn't reproduce this. Could you confirm your version with `pip freeze`?

**Comment by TaoTaotheCreator** [comment]
![pip](https://github.com/user-attachments/assets/2525551b-7b69-4a96-8866-1731c92b385f)
My python version is 3.7 (as stated in wiki), maybe I need to update to higher python version to use the higher version Numpy?

**Comment by ondrejkrejci** [comment]
Hi, it is not a numpy problem, it is actually bug comming from ppafm changes has not been implemented properly in PPSTM. We are working on it.

**Comment by LauriKurki** [comment]
Hey @TaoTaotheCreator, there's a fix for this on the updated master branch, could you check if this problem is solved?

**Comment by TaoTaotheCreator** [comment]
Okay:)

**Comment by TaoTaotheCreator** [comment]
Yes, I got the simulated images using random tip orbital proportion. Thank you all!
